FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV container=docker

RUN apt-get update && \
    apt-get install -y \
      systemd systemd-sysv dbus dbus-x11 \
      gnome-shell ubuntu-desktop-minimal gdm3 \
      x11vnc novnc websockify \
      xvfb sudo locales && \
    apt-get clean

RUN locale-gen en_US.UTF-8 ja_JP.UTF-8 && \
    update-locale LANG=ja_JP.UTF-8

RUN useradd -m -s /bin/bash gnome && \
    echo 'gnome ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/gnome

RUN systemctl set-default graphical.target || true

COPY start-gnome-vnc.sh /usr/local/bin/start-gnome-vnc.sh
COPY gnome-vnc.service /etc/systemd/system/gnome-vnc.service

RUN chmod +x /usr/local/bin/start-gnome-vnc.sh

CMD ["/lib/systemd/systemd"]
